### ISSUE TITLE
Please provide examples using javascript. Not typescript.

### ISSUE THREAD

**Issue by haducloc** [persevie/statemanjs#2]
Sorry I am new to TypeScript. I know JavaScript only. I am developing a web application using Google Lit-Html ( NOT Lit-Element).  In this application, I am using global variables to store states. It is working fine.

I want to move to use statemanjs to manage the Lit-Html model state by using JavaScript ( Not TypeScript). Is it possible? Thanks!

**Comment by dmtrshat** [comment]
@haducloc here is an example with lit-html:
```js
const clickState = createState(0);

const myTemplate = (clicks) =>
  html`<button @click=${clickHandler}>Clicks: ${clicks}</button>`;

function clickHandler() {
  clickState.set(clickState.get() + 1);
}

render(myTemplate(clickState.get()), document.body);

clickState.subscribe((s) => {
  render(myTemplate(s), document.body);
});
```

**Comment by dmtrshat** [comment]
> Thank you very much! I will give it a try. Really like your simpler solution to manage state in JavaScript application!

Thank you 😊
